# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('topic_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=60)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('total_questions', models.IntegerField()),
                ('sub_topics', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='LatestFetchDate',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latest_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField()),
                ('correct_questions', models.IntegerField()),
                ('attempt_questions', models.IntegerField()),
                ('students_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField()),
                ('correct_questions', models.IntegerField()),
                ('attempt_questions', models.IntegerField()),
                ('students_completed', models.IntegerField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.Content')),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField()),
                ('correct_questions', models.IntegerField()),
                ('attempt_questions', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.Content')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoClass',
            fields=[
                ('class_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=60)),
                ('total_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoSchool',
            fields=[
                ('school_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=60)),
                ('total_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoStudent',
            fields=[
                ('student_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoClass')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleCollectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approver_id', models.IntegerField(null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoClass')),
                ('institute_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoSchool')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_failed_attempts', models.IntegerField()),
                ('last_login_time', models.DateTimeField(null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(null=True)),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userrolecollectionmapping',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.Users'),
        ),
        migrations.AddField(
            model_name='userinfoclass',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoSchool'),
        ),
        migrations.AddField(
            model_name='masterylevelstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoStudent'),
        ),
        migrations.AddField(
            model_name='masterylevelschool',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoSchool'),
        ),
        migrations.AddField(
            model_name='masterylevelclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoClass'),
        ),
        migrations.AddField(
            model_name='masterylevelclass',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.Content'),
        ),
    ]
