# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoclass',
            name='parent',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfostudent',
            name='parent',
            field=models.BigIntegerField(),
        ),
    ]
