# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('topic_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=140)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('total_questions', models.IntegerField()),
                ('sub_topics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestFetchDate',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latest_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelClass',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('attempt_questions', models.IntegerField(default=0)),
                ('students_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelSchool',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('attempt_questions', models.IntegerField(default=0)),
                ('students_completed', models.IntegerField(default=0)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoSchool')),
            ],
        ),
        migrations.CreateModel(
            name='MasteryLevelStudent',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('attempt_questions', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoStudent',
            fields=[
                ('student_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('parent', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='userinfoclass',
            name='parent',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='masterylevelstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoStudent'),
        ),
        migrations.AddField(
            model_name='masterylevelclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nalanda.UserInfoClass'),
        ),
    ]
