# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0002_auto_20170710_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topic_name',
            field=models.CharField(max_length=140),
        ),
    ]
