# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0004_auto_20170710_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterylevelclass',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylevelschool',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylevelstudent',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
