# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0005_auto_20170710_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterylevelclass',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylevelschool',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='masterylevelstudent',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
