# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalanda', '0009_auto_20170710_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterylevelclass',
            name='content_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='masterylevelschool',
            name='content_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='masterylevelstudent',
            name='content_id',
            field=models.CharField(max_length=32),
        ),
    ]
