# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleCollectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_failed_attempts', models.IntegerField()),
                ('facility_id', models.IntegerField()),
                ('approver_id', models.IntegerField()),
                ('last_login_time', models.DateField()),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='userrolecollectionmapping',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Users'),
        ),
    ]
